# coding: utf-8

"""
    Payments API Gateway

    This is an internal payments API gateway for Chamaconekt Kenya 

    OpenAPI spec version: 0.1
    Contact: ondengew@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """ AccountApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.account_api.AccountApi()

    def tearDown(self):
        pass

    def test_account_create(self):
        """
        Test case for account_create

        create account
        """
        pass

    def test_account_delete(self):
        """
        Test case for account_delete

        delete account
        """
        pass

    def test_account_list(self):
        """
        Test case for account_list

        list account
        """
        pass

    def test_account_show(self):
        """
        Test case for account_show

        show account
        """
        pass

    def test_account_update(self):
        """
        Test case for account_update

        update account
        """
        pass


if __name__ == '__main__':
    unittest.main()
