# coding: utf-8

"""
    Payments API Gateway

    This is an internal payments API gateway for Chamaconekt Kenya 

    OpenAPI spec version: 0.1
    Contact: ondengew@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.b2_c_payload import B2CPayload


class TestB2CPayload(unittest.TestCase):
    """ B2CPayload unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testB2CPayload(self):
        """
        Test B2CPayload
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.b2_c_payload.B2CPayload()
        pass


if __name__ == '__main__':
    unittest.main()
