# coding: utf-8

"""
    Mpesa  Service

    This is an internal Mpesa Service that communicates via REST to the Safaricom Daraja API

    OpenAPI spec version: 1.0
    Contact: ondengew@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.b2_c_payload_1 import B2CPayload1


class TestB2CPayload1(unittest.TestCase):
    """ B2CPayload1 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testB2CPayload1(self):
        """
        Test B2CPayload1
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.b2_c_payload_1.B2CPayload1()
        pass


if __name__ == '__main__':
    unittest.main()
