# coding: utf-8

"""
    Payments API Gateway

    This is an internal payments API gateway for Chamaconekt Kenya 

    OpenAPI spec version: 0.1
    Contact: ondengew@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.b2c_api import B2cApi


class TestB2cApi(unittest.TestCase):
    """ B2cApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.b2c_api.B2cApi()

    def tearDown(self):
        pass

    def test_b2c_create(self):
        """
        Test case for b2c_create

        create b2c
        """
        pass


if __name__ == '__main__':
    unittest.main()
