# coding: utf-8

"""
    Payments API Gateway

    This is an internal payments API gateway for Chamaconekt Kenya 

    OpenAPI spec version: 0.1
    Contact: ondengew@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_js_js_filepath(self):
        """
        Test case for js_js_filepath

        Download public/js
        """
        pass

    def test_public_ui(self):
        """
        Test case for public_ui

        Download public/html/index.html
        """
        pass

    def test_swagger_swagger_json(self):
        """
        Test case for swagger_swagger_json

        Download public/swagger/swagger.json
        """
        pass


if __name__ == '__main__':
    unittest.main()
