# coding: utf-8

"""
    Payments API Gateway

    This is an internal payments API gateway for Chamaconekt Kenya 

    OpenAPI spec version: 0.1
    Contact: ondengew@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Payments API Gateway",
    author_email="ondengew@gmail.com",
    url="",
    keywords=["Swagger", "Payments API Gateway"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is an internal payments API gateway for Chamaconekt Kenya 
    """
)
