# coding: utf-8

"""
    Mpesa  Service

    This is an internal Mpesa Service that communicates via REST to the Safaricom Daraja API

    OpenAPI spec version: 1.0
    Contact: ondengew@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .b2_c_payload import B2CPayload
from .b2_c_payload_1 import B2CPayload1
